### ISSUE TITLE
Issues with sunbird-ed-installer

### ISSUE THREAD

**Issue by raghupathiguduri** [project-sunbird/sunbird-ed-installer#56]
Hi Team, 

As we are integrating the ml related services into ed-installer, we wanted to test the functionality of ml services by installing the sunbird setup using this ed-installer. But we are facing challanges for installing it.

1.Error with service providers registration, Script is not registring the services if not registered manually. Also there is no list of services which needs to registered at subscription level.
2.Permission error while creating AKS cluster
    For this User needs Application Administration role in Azure Active Directory to perform the installation.
3.Standard Basv2 Family vCPUs are not available in Central India region. 
![image](https://github.com/project-sunbird/sunbird-ed-installer/assets/48198006/0caa3b5c-68f3-4668-bacf-c47966936dd8)

4.While using release-6.0.0, installation is getting struck at lms as the pods are crashlooping with error message. Attach the lms logs at the end.
5.While using release-7.0.0 installation is successful but login is not working and it is throwing the error below.

**lms service log with error when using release-6.0.0**
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/sunbird/lms/lms-service-1.0-SNAPSHOT/lib/ch.qos.logback.logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/sunbird/lms/lms-service-1.0-SNAPSHOT/lib/org.sunbird.sunbird-commons-1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcI$sp
	at com.fasterxml.jackson.module.scala.JacksonModule$.version$lzycompute(JacksonModule.scala:31)
	at com.fasterxml.jackson.module.scala.JacksonModule$.version(JacksonModule.scala:26)
	at com.fasterxml.jackson.module.scala.JacksonModule.version(JacksonModule.scala:49)
	at com.fasterxml.jackson.module.scala.JacksonModule.version$(JacksonModule.scala:49)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.version(DefaultScalaModule.scala:18)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:781)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModules(ObjectMapper.java:1010)
	at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1088)
	at net.logstash.logback.composite.CompositeJsonFormatter.createJsonFactory(CompositeJsonFormatter.java:131)
	at net.logstash.logback.composite.CompositeJsonFormatter.start(CompositeJsonFormatter.java:104)
	at net.logstash.logback.LogstashFormatter.start(LogstashFormatter.java:154)
	at net.logstash.logback.encoder.CompositeJsonEncoder.start(CompositeJsonEncoder.java:211)
	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.end(NestedComplexPropertyIA.java:161)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at play.api.Logger$.<init>(Logger.scala:291)
	at play.api.Logger$.<clinit>(Logger.scala)
	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:73)
	at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$1.apply(GuiceApplicationBuilder.scala:138)
	at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$1.apply(GuiceApplicationBuilder.scala:137)
	at scala.Option.map(Option.scala:146)
	at play.api.inject.guice.GuiceApplicationBuilder.configureLoggerFactory(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:113)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:201)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:156)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:22)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:59)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:31)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.ClassNotFoundException: scala.runtime.java8.JFunction0$mcI$sp
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 43 more
Exception in thread "main" java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcI$sp
	at com.fasterxml.jackson.module.scala.JacksonModule$.version$lzycompute(JacksonModule.scala:31)
	at com.fasterxml.jackson.module.scala.JacksonModule$.version(JacksonModule.scala:26)
	at com.fasterxml.jackson.module.scala.JacksonModule.version(JacksonModule.scala:49)
	at com.fasterxml.jackson.module.scala.JacksonModule.version$(JacksonModule.scala:49)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.version(DefaultScalaModule.scala:18)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:781)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModules(ObjectMapper.java:1010)
	at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1088)
	at net.logstash.logback.composite.CompositeJsonFormatter.createJsonFactory(CompositeJsonFormatter.java:131)
	at net.logstash.logback.composite.CompositeJsonFormatter.start(CompositeJsonFormatter.java:104)
	at net.logstash.logback.LogstashFormatter.start(LogstashFormatter.java:154)
	at net.logstash.logback.encoder.CompositeJsonEncoder.start(CompositeJsonEncoder.java:211)
	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.end(NestedComplexPropertyIA.java:161)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at play.api.Logger$.<init>(Logger.scala:291)
	at play.api.Logger$.<clinit>(Logger.scala)
	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:73)
	at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$1.apply(GuiceApplicationBuilder.scala:138)
	at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$1.apply(GuiceApplicationBuilder.scala:137)
	at scala.Option.map(Option.scala:146)
	at play.api.inject.guice.GuiceApplicationBuilder.configureLoggerFactory(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:113)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:201)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:156)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:22)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:59)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:31)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.ClassNotFoundException: scala.runtime.java8.JFunction0$mcI$sp
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 43 more

**Error in console while installed using release-7.0.0**
telemetry_service.js?v=1.15.b:2593 Uncaught TypeError: Cannot read properties of undefined (reading 'hashTagId')
    at logInteractEvent (telemetry_service.js?v=1.15.b:2593:26)
    at doLogin (telemetry_service.js?v=1.15.b:2619:5)
    at HTMLButtonElement.onclick (auth?client_id=portal&state=63099374-a325-4a0b-8190-33afec5e8803&redirect_uri=https%3A%2F%2Fsunbird-test.xyz%2Fresources%3Fauth_callback%3D1&scope=openid&response_type=code&version=4:89:129)
logInteractEvent @ telemetry_service.js?v=1.15.b:2593
doLogin @ telemetry_service.js?v=1.15.b:2619
onclick @ auth?client_id=portal&state=63099374-a325-4a0b-8190-33afec5e8803&redirect_uri=https%3A%2F%2Fsunbird-test.xyz%2Fresources%3Fauth_callback%3D1&scope=openid&response_type=code&version=4:89
telemetry_service.js?v=1.15.b:2593 Uncaught TypeError: Cannot read properties of undefined (reading 'hashTagId')
    at logInteractEvent (telemetry_service.js?v=1.15.b:2593:26)
    at navigate (telemetry_service.js?v=1.15.b:3028:11)
    at HTMLSpanElement.onclick (auth?client_id=portal&state=63099374-a325-4a0b-8190-33afec5e8803&redirect_uri=https%3A%2F%2Fsunbird-test.xyz%2Fresources%3Fauth_callback%3D1&scope=openid&response_type=code&version=4:93:153)

Also we got this at the end of script execution after the DNS propagation.
Starting post install...
Could not get the lock, quitting
Gtk-Message: 01:15:34.313: Failed to load module "canberra-gtk-module"
Gtk-Message: 01:15:34.316: Failed to load module "canberra-gtk-module"
[84746:0607/011534.367149:ERROR:angle_platform_impl.cc(43)] Display.cpp:992 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
[84746:0607/011534.367319:ERROR:gl_surface_egl.cc(831)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
[84746:0607/011534.367392:ERROR:gl_surface_egl.cc(1353)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[84746:0607/011534.367951:ERROR:angle_platform_impl.cc(43)] Display.cpp:992 (initialize): ANGLE Display::initialize error 12289: Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
[84746:0607/011534.368068:ERROR:gl_surface_egl.cc(831)] EGL Driver message (Critical) eglInitialize: Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
[84746:0607/011534.368145:ERROR:gl_surface_egl.cc(1353)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[84746:0607/011534.368207:ERROR:gl_ozone_egl.cc(23)] GLSurfaceEGL::InitializeOneOff failed.
[84746:0607/011534.370572:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization

Kindly let us know if there is any particular branch/tag tested or if there are any post installation steps missed in instructions.

**Comment by gandham-santhosh** [comment]
@raghupathiguduri  Dont use release-7.0.0 as it is still in testing phase.  release-6.0.0 branch is the working one.

Looks like lms service is not loading the class while bootstrapping. Can you redeploy the Lern helm chart alone and check by using the following command?
`helm install lern -n sunbird`

**Comment by sanketnagdive** [comment]
@raghupathiguduri You even can explicitly call helm function in install.sh by running `./install.sh install_helm_components helmchartname`
